-- =============================================================================
-- seeds/001_admin_profile.sql
-- No pre-created admin. After first deployment:
--
-- 1. Sign up normally at /sign-up
-- 2. Complete onboarding (pick Educator role)
-- 3. Run the following in Supabase SQL Editor, replacing the email:
--
--    UPDATE profiles
--    SET is_admin = true, approval_status = 'approved'
--    WHERE email = 'your@email.com';
--
-- 4. Sign out and sign back in — you will land on /admin
-- =============================================================================
